name: nested_reorderable_list_example
description: Sample project
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  nested_reorderable_list:
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic_mono:
dependency_overrides:
  nested_reorderable_list:
    path: ../
flutter:
  uses-material-design: true
