name: nested_reorderable_list
description: Nested Reorderable List
version: 0.0.1
repository: https://github.com/welchi/nested_reorderable_list

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
